<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\WordController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\TagController;

Route::get('/home', function () {
    return response()->json([
        "message" => "API funcionando",

        "cards" => [
            [
                "icon" => "cpu",
                "word" => "Algorithm",
                "pronunciation" => "ál-go-ri-dhm",
                "translation" => "Algoritmo",
                "desc" => "Sequência de passos para resolver um problema.",
            ],
            [
                "icon" => "shield",
                "word" => "Authentication",
                "pronunciation" => "au-then-ti-kêi-shun",
                "translation" => "Autenticação",
                "desc" => "Processo de verificar identidade.",
            ],
            [
                "icon" => "settings",
                "word" => "API",
                "pronunciation" => "êi-pi-ai",
                "translation" => "API",
                "desc" => "Interface para comunicação entre sistemas.",
            ],
            [
                "icon" => "sliders",
                "word" => "Access",
                "pronunciation" => "ék-ses",
                "translation" => "Acesso",
                "desc" => "Permissão para usar recursos.",
            ],
            [
                "icon" => "box",
                "word" => "Attribute",
                "pronunciation" => "á-tri-biúti",
                "translation" => "Atributo",
                "desc" => "Característica de um objeto.",
            ],
            [
                "icon" => "layers",
                "word" => "Architecture",
                "pronunciation" => "ár-ki-tek-chur",
                "translation" => "Arquitetura",
                "desc" => "Estrutura de um sistema.",
            ],

            // B
            [
                "icon" => "tool",
                "word" => "Backend",
                "pronunciation" => "bé-ken-d",
                "translation" => "Backend",
                "desc" => "Parte do sistema que roda no servidor.",
            ],
            [
                "icon" => "layout",
                "word" => "Boolean",
                "pronunciation" => "bú-li-an",
                "translation" => "Booleano",
                "desc" => "Tipo de dado verdadeiro ou falso.",
            ],
            [
                "icon" => "database",
                "word" => "Backup",
                "pronunciation" => "bé-kap",
                "translation" => "Backup",
                "desc" => "Cópia de segurança dos dados.",
            ],
            [
                "icon" => "bug",
                "word" => "Bug",
                "pronunciation" => "bâg",
                "translation" => "Erro",
                "desc" => "Falha em um sistema ou código.",
            ],
            [
                "icon" => "activity",
                "word" => "Bandwidth",
                "pronunciation" => "bând-uíd-th",
                "translation" => "Largura de banda",
                "desc" => "Quantidade de dados transmitidos.",
            ],
            [
                "icon" => "git-branch",
                "word" => "Branch",
                "pronunciation" => "brânch",
                "translation" => "Ramificação",
                "desc" => "Linha paralela de desenvolvimento.",
            ],

            // C
            [
                "icon" => "monitor",
                "word" => "Cache",
                "pronunciation" => "kæsh (késh)",
                "translation" => "Cache",
                "desc" => "Armazenamento temporário para acelerar processos.",
            ],
            [
                "icon" => "terminal",
                "word" => "Command",
                "pronunciation" => "ko-mánd",
                "translation" => "Comando",
                "desc" => "Instrução executada no sistema.",
            ],
            [
                "icon" => "git-merge",
                "word" => "Commit",
                "pronunciation" => "co-mít",
                "translation" => "Commit",
                "desc" => "Salvar alterações no versionamento.",
            ],
            [
                "icon" => "code",
                "word" => "Compiler",
                "pronunciation" => "com-pái-ler",
                "translation" => "Compilador",
                "desc" => "Traduz código para linguagem de máquina.",
            ],
            [
                "icon" => "cloud",
                "word" => "Container",
                "pronunciation" => "con-têi-ner",
                "translation" => "Container",
                "desc" => "Ambiente isolado para aplicações.",
            ],
            [
                "icon" => "shield",
                "word" => "Cybersecurity",
                "pronunciation" => "sai-ber-si-kiu-ri-ti",
                "translation" => "Cibersegurança",
                "desc" => "Proteção de sistemas e dados.",
            ],

            // D
            [
                "icon" => "database",
                "word" => "Database",
                "pronunciation" => "dêi-ta-bêis",
                "translation" => "Banco de dados",
                "desc" => "Sistema de armazenamento de dados.",
            ],
            [
                "icon" => "cpu",
                "word" => "Debug",
                "pronunciation" => "di-bâg",
                "translation" => "Depurar",
                "desc" => "Corrigir erros no código.",
            ],
            [
                "icon" => "git-merge",
                "word" => "Deploy",
                "pronunciation" => "di-plói",
                "translation" => "Implantar",
                "desc" => "Colocar sistema em produção.",
            ],
            [
                "icon" => "download",
                "word" => "Download",
                "pronunciation" => "dáun-lôud",
                "translation" => "Baixar",
                "desc" => "Transferir dados da internet.",
            ],
            [
                "icon" => "hard-drive",
                "word" => "Disk",
                "pronunciation" => "dísk",
                "translation" => "Disco",
                "desc" => "Armazenamento físico de dados.",
            ],
            [
                "icon" => "code",
                "word" => "DOM",
                "pronunciation" => "dó-em",
                "translation" => "DOM",
                "desc" => "Estrutura de elementos HTML.",
            ],

            // E
            [
                "icon" => "mail",
                "word" => "Email",
                "pronunciation" => "í-meil",
                "translation" => "Email",
                "desc" => "Mensagem eletrônica.",
            ],
            [
                "icon" => "zap",
                "word" => "Event",
                "pronunciation" => "i-vént",
                "translation" => "Evento",
                "desc" => "Ação detectada pelo sistema.",
            ],
            [
                "icon" => "code",
                "word" => "Exception",
                "pronunciation" => "ek-sép-shun",
                "translation" => "Exceção",
                "desc" => "Erro em tempo de execução.",
            ],
            [
                "icon" => "cpu",
                "word" => "Execution",
                "pronunciation" => "ek-se-kiu-shun",
                "translation" => "Execução",
                "desc" => "Processo de rodar um programa.",
            ],
            [
                "icon" => "server",
                "word" => "Endpoint",
                "pronunciation" => "énd-point",
                "translation" => "Endpoint",
                "desc" => "Ponto de acesso de uma API.",
            ],
            [
                "icon" => "activity",
                "word" => "Encryption Key",
                "pronunciation" => "en-críp-shun kí",
                "translation" => "Chave de criptografia",
                "desc" => "Código usado para criptografar dados.",
            ],

            // F
            [
                "icon" => "monitor",
                "word" => "Frontend",
                "pronunciation" => "frânt-end",
                "translation" => "Frontend",
                "desc" => "Parte visual do sistema.",
            ],
            [
                "icon" => "filter",
                "word" => "Filter",
                "pronunciation" => "fíl-ter",
                "translation" => "Filtro",
                "desc" => "Seleciona dados específicos.",
            ],
            [
                "icon" => "file",
                "word" => "File",
                "pronunciation" => "fáil",
                "translation" => "Arquivo",
                "desc" => "Unidade de armazenamento de dados.",
            ],
            [
                "icon" => "cpu",
                "word" => "Framework",
                "pronunciation" => "frêim-uork",
                "translation" => "Framework",
                "desc" => "Base para desenvolvimento de software.",
            ],
            [
                "icon" => "shield",
                "word" => "Firewall",
                "pronunciation" => "fái-er-uól",
                "translation" => "Firewall",
                "desc" => "Proteção contra acessos indevidos.",
            ],
            [
                "icon" => "search",
                "word" => "Fetch",
                "pronunciation" => "fé-tch",
                "translation" => "Buscar",
                "desc" => "Obter dados de uma fonte.",
            ],
            [
                "icon" => "github",
                "word" => "Git",
                "pronunciation" => "guit",
                "translation" => "Git",
                "desc" => "Sistema de controle de versão.",
            ],
            [
                "icon" => "git-merge",
                "word" => "GitHub",
                "pronunciation" => "guit-râb",
                "translation" => "GitHub",
                "desc" => "Plataforma para hospedar código.",
            ],
            [
                "icon" => "activity",
                "word" => "GPU",
                "pronunciation" => "djí-pi-iu",
                "translation" => "GPU",
                "desc" => "Processador gráfico.",
            ],
            [
                "icon" => "database",
                "word" => "Garbage Collection",
                "pronunciation" => "gár-bâj co-lék-shun",
                "translation" => "Coleta de lixo",
                "desc" => "Liberação automática de memória.",
            ],
            [
                "icon" => "bar-chart",
                "word" => "GraphQL",
                "pronunciation" => "gráf-kiu-él",
                "translation" => "GraphQL",
                "desc" => "Linguagem de consulta para APIs.",
            ],
            [
                "icon" => "globe",
                "word" => "Gateway",
                "pronunciation" => "guêit-uêi",
                "translation" => "Gateway",
                "desc" => "Ponto de conexão entre redes.",
            ],

            // H
            [
                "icon" => "globe",
                "word" => "HTTP",
                "pronunciation" => "êitch-ti-ti-pi",
                "translation" => "HTTP",
                "desc" => "Protocolo de comunicação web.",
            ],
            [
                "icon" => "lock",
                "word" => "HTTPS",
                "pronunciation" => "êitch-ti-ti-pi-és",
                "translation" => "HTTPS",
                "desc" => "HTTP seguro com criptografia.",
            ],
            [
                "icon" => "hard-drive",
                "word" => "Hardware",
                "pronunciation" => "rárd-uér",
                "translation" => "Hardware",
                "desc" => "Parte física do computador.",
            ],
            [
                "icon" => "home",
                "word" => "Host",
                "pronunciation" => "rôust",
                "translation" => "Hospedeiro",
                "desc" => "Servidor ou máquina que fornece serviços.",
            ],
            [
                "icon" => "clock",
                "word" => "Hash",
                "pronunciation" => "résh",
                "translation" => "Hash",
                "desc" => "Função que gera código único.",
            ],
            [
                "icon" => "server",
                "word" => "Hosting",
                "pronunciation" => "rôus-ting",
                "translation" => "Hospedagem",
                "desc" => "Serviço para manter sites online.",
            ],

            // I
            [
                "icon" => "cpu",
                "word" => "IDE",
                "pronunciation" => "ai-di-i",
                "translation" => "IDE",
                "desc" => "Ambiente de desenvolvimento.",
            ],
            [
                "icon" => "wifi",
                "word" => "Internet",
                "pronunciation" => "ín-ter-net",
                "translation" => "Internet",
                "desc" => "Rede global de computadores.",
            ],
            [
                "icon" => "share-2",
                "word" => "IP",
                "pronunciation" => "ai-pi",
                "translation" => "IP",
                "desc" => "Endereço de um dispositivo na rede.",
            ],
            [
                "icon" => "settings",
                "word" => "Input",
                "pronunciation" => "ín-put",
                "translation" => "Entrada",
                "desc" => "Dados inseridos no sistema.",
            ],
            [
                "icon" => "download",
                "word" => "Install",
                "pronunciation" => "in-stól",
                "translation" => "Instalar",
                "desc" => "Adicionar software ao sistema.",
            ],
            [
                "icon" => "code",
                "word" => "Iteration",
                "pronunciation" => "i-te-rêi-shun",
                "translation" => "Iteração",
                "desc" => "Repetição de um processo.",
            ],

            // J
            [
                "icon" => "code",
                "word" => "Java",
                "pronunciation" => "djá-va",
                "translation" => "Java",
                "desc" => "Linguagem de programação.",
            ],
            [
                "icon" => "codepen",
                "word" => "JSON",
                "pronunciation" => "djêi-sân",
                "translation" => "JSON",
                "desc" => "Formato de troca de dados.",
            ],
            [
                "icon" => "terminal",
                "word" => "JDK",
                "pronunciation" => "djêi-di-kêi",
                "translation" => "JDK",
                "desc" => "Kit de desenvolvimento Java.",
            ],
            [
                "icon" => "zap",
                "word" => "Job",
                "pronunciation" => "djób",
                "translation" => "Tarefa",
                "desc" => "Processo executado pelo sistema.",
            ],
            [
                "icon" => "cpu",
                "word" => "JIT",
                "pronunciation" => "djêi-ai-ti",
                "translation" => "JIT",
                "desc" => "Compilação em tempo de execução.",
            ],
            [
                "icon" => "activity",
                "word" => "JVM",
                "pronunciation" => "djêi-vi-ém",
                "translation" => "JVM",
                "desc" => "Máquina virtual Java.",
            ],

            // K
            [
                "icon" => "cpu",
                "word" => "Kernel",
                "pronunciation" => "kér-nel",
                "translation" => "Kernel",
                "desc" => "Núcleo do sistema operacional.",
            ],
            [
                "icon" => "lock",
                "word" => "Key Pair",
                "pronunciation" => "kí pêr",
                "translation" => "Par de chaves",
                "desc" => "Chaves pública e privada.",
            ],
            [
                "icon" => "hard-drive",
                "word" => "Kilobyte",
                "pronunciation" => "kí-lo-báit",
                "translation" => "Kilobyte",
                "desc" => "Unidade de dados.",
            ],
            [
                "icon" => "activity",
                "word" => "KPI",
                "pronunciation" => "kêi-pi-ai",
                "translation" => "Indicador",
                "desc" => "Métrica de desempenho.",
            ],
            [
                "icon" => "box",
                "word" => "Kubernetes",
                "pronunciation" => "ku-ber-né-tis",
                "translation" => "Kubernetes",
                "desc" => "Orquestra containers.",
            ],
            [
                "icon" => "cpu",
                "word" => "Keystroke",
                "pronunciation" => "kí-strôuk",
                "translation" => "Tecla pressionada",
                "desc" => "Entrada do teclado.",
            ],

            // L
            [
                "icon" => "code",
                "word" => "Library",
                "pronunciation" => "lái-bre-ri",
                "translation" => "Biblioteca",
                "desc" => "Conjunto de códigos reutilizáveis.",
            ],
            [
                "icon" => "link",
                "word" => "Link",
                "pronunciation" => "línk",
                "translation" => "Link",
                "desc" => "Ligação entre recursos.",
            ],
            [
                "icon" => "repeat",
                "word" => "Loop",
                "pronunciation" => "lúp",
                "translation" => "Loop",
                "desc" => "Repetição de código.",
            ],
            [
                "icon" => "cpu",
                "word" => "Linux",
                "pronunciation" => "lí-nuks",
                "translation" => "Linux",
                "desc" => "Sistema operacional.",
            ],
            [
                "icon" => "file",
                "word" => "Log",
                "pronunciation" => "lóg",
                "translation" => "Log",
                "desc" => "Registro de eventos.",
            ],
            [
                "icon" => "layout",
                "word" => "Layout",
                "pronunciation" => "lêi-aut",
                "translation" => "Layout",
                "desc" => "Estrutura visual.",
            ],
            // M
            [
                "icon" => "box",
                "word" => "Model",
                "pronunciation" => "mó-del",
                "translation" => "Modelo",
                "desc" => "Representação de dados no sistema.",
            ],
            [
                "icon" => "cpu",
                "word" => "Middleware",
                "pronunciation" => "míd-uér",
                "translation" => "Middleware",
                "desc" => "Camada entre requisição e resposta.",
            ],
            [
                "icon" => "hard-drive",
                "word" => "Memory Leak",
                "pronunciation" => "mé-mo-ri lík",
                "translation" => "Vazamento de memória",
                "desc" => "Uso incorreto de memória não liberada.",
            ],
            [
                "icon" => "git-merge",
                "word" => "Merge",
                "pronunciation" => "mérj",
                "translation" => "Mesclar",
                "desc" => "Unir alterações de código.",
            ],
            [
                "icon" => "monitor",
                "word" => "Mobile",
                "pronunciation" => "mô-báil",
                "translation" => "Mobile",
                "desc" => "Dispositivos móveis.",
            ],
            [
                "icon" => "settings",
                "word" => "Module",
                "pronunciation" => "mó-djul",
                "translation" => "Módulo",
                "desc" => "Parte independente de um sistema.",
            ],

            // N
            [
                "icon" => "server",
                "word" => "Network",
                "pronunciation" => "nét-uork",
                "translation" => "Rede",
                "desc" => "Conexão entre dispositivos.",
            ],
            [
                "icon" => "code",
                "word" => "Node",
                "pronunciation" => "nôud",
                "translation" => "Nó",
                "desc" => "Elemento em uma rede ou sistema.",
            ],
            [
                "icon" => "file",
                "word" => "Null",
                "pronunciation" => "nâl",
                "translation" => "Nulo",
                "desc" => "Valor vazio ou inexistente.",
            ],
            [
                "icon" => "activity",
                "word" => "Namespace",
                "pronunciation" => "nêim-spêis",
                "translation" => "Namespace",
                "desc" => "Agrupamento lógico de código.",
            ],
            [
                "icon" => "cpu",
                "word" => "NPM",
                "pronunciation" => "én-pi-ém",
                "translation" => "NPM",
                "desc" => "Gerenciador de pacotes Node.",
            ],
            [
                "icon" => "wifi",
                "word" => "Node.js",
                "pronunciation" => "nôud-djê-és",
                "translation" => "Node.js",
                "desc" => "JavaScript no backend.",
            ],

            // O
            [
                "icon" => "box",
                "word" => "Object-Oriented",
                "pronunciation" => "ób-djékt ó-ri-en-ted",
                "translation" => "Orientado a objetos",
                "desc" => "Paradigma de programação.",
            ],
            [
                "icon" => "cpu",
                "word" => "Optimization",
                "pronunciation" => "óp-ti-mai-zêi-shun",
                "translation" => "Otimização",
                "desc" => "Melhoria de desempenho.",
            ],
            [
                "icon" => "settings",
                "word" => "Output",
                "pronunciation" => "áut-put",
                "translation" => "Saída",
                "desc" => "Resultado de um processo.",
            ],
            [
                "icon" => "database",
                "word" => "ORM",
                "pronunciation" => "ó-ar-ém",
                "translation" => "ORM",
                "desc" => "Mapeamento objeto-relacional.",
            ],
            [
                "icon" => "globe",
                "word" => "Open Source",
                "pronunciation" => "ôu-pen sórs",
                "translation" => "Código aberto",
                "desc" => "Software com código disponível.",
            ],
            [
                "icon" => "cpu",
                "word" => "Overload",
                "pronunciation" => "ôu-ver-lôud",
                "translation" => "Sobrecarga",
                "desc" => "Excesso de uso de recursos.",
            ],

            // P
            [
                "icon" => "code",
                "word" => "Programming",
                "pronunciation" => "prô-gra-ming",
                "translation" => "Programação",
                "desc" => "Escrever código para sistemas.",
            ],
            [
                "icon" => "server",
                "word" => "Protocol",
                "pronunciation" => "prô-to-cól",
                "translation" => "Protocolo",
                "desc" => "Regras de comunicação.",
            ],
            [
                "icon" => "cpu",
                "word" => "Process",
                "pronunciation" => "pró-sés",
                "translation" => "Processo",
                "desc" => "Programa em execução.",
            ],
            [
                "icon" => "shield",
                "word" => "Permission",
                "pronunciation" => "per-mí-shun",
                "translation" => "Permissão",
                "desc" => "Controle de acesso.",
            ],
            [
                "icon" => "layers",
                "word" => "Package",
                "pronunciation" => "pá-kej",
                "translation" => "Pacote",
                "desc" => "Conjunto de arquivos/código.",
            ],
            [
                "icon" => "code",
                "word" => "Pointer",
                "pronunciation" => "pói-ter",
                "translation" => "Ponteiro",
                "desc" => "Referência de memória.",
            ],

            // Q
            [
                "icon" => "search",
                "word" => "Query",
                "pronunciation" => "cuí-ri",
                "translation" => "Consulta",
                "desc" => "Busca em banco de dados.",
            ],
            [
                "icon" => "database",
                "word" => "Queue",
                "pronunciation" => "kiu",
                "translation" => "Fila",
                "desc" => "Estrutura FIFO.",
            ],
            [
                "icon" => "activity",
                "word" => "Quick Sort",
                "pronunciation" => "kuík sórt",
                "translation" => "Quick Sort",
                "desc" => "Algoritmo de ordenação.",
            ],
            [
                "icon" => "cpu",
                "word" => "Quantum Computing",
                "pronunciation" => "kuân-tum com-piu-ting",
                "translation" => "Computação quântica",
                "desc" => "Processamento avançado.",
            ],
            [
                "icon" => "file",
                "word" => "Queue Job",
                "pronunciation" => "kiu djób",
                "translation" => "Job em fila",
                "desc" => "Tarefa assíncrona.",
            ],
            [
                "icon" => "settings",
                "word" => "Quota",
                "pronunciation" => "kuô-ta",
                "translation" => "Cota",
                "desc" => "Limite de uso.",
            ],

            // R
            [
                "icon" => "server",
                "word" => "REST",
                "pronunciation" => "rést",
                "translation" => "REST",
                "desc" => "Arquitetura de APIs.",
            ],
            [
                "icon" => "send",
                "word" => "Request",
                "pronunciation" => "ri-kuést",
                "translation" => "Requisição",
                "desc" => "Pedido ao servidor.",
            ],
            [
                "icon" => "download",
                "word" => "Response",
                "pronunciation" => "ri-spóns",
                "translation" => "Resposta",
                "desc" => "Retorno do servidor.",
            ],
            [
                "icon" => "repeat",
                "word" => "Recursion",
                "pronunciation" => "ri-kâr-shun",
                "translation" => "Recursão",
                "desc" => "Função que chama a si mesma.",
            ],
            [
                "icon" => "cpu",
                "word" => "Runtime",
                "pronunciation" => "rân-taim",
                "translation" => "Tempo de execução",
                "desc" => "Momento em que o código roda.",
            ],
            [
                "icon" => "rotate-cw",
                "word" => "Render",
                "pronunciation" => "rén-der",
                "translation" => "Renderizar",
                "desc" => "Exibir na tela.",
            ],
            // S
            [
                "icon" => "server",
                "word" => "Server",
                "pronunciation" => "sér-ver",
                "translation" => "Servidor",
                "desc" => "Máquina que fornece serviços.",
            ],
            [
                "icon" => "database",
                "word" => "SQL",
                "pronunciation" => "és-kiu-él",
                "translation" => "SQL",
                "desc" => "Linguagem de banco de dados.",
            ],
            [
                "icon" => "shield",
                "word" => "Security",
                "pronunciation" => "si-kiu-ri-ti",
                "translation" => "Segurança",
                "desc" => "Proteção de sistemas.",
            ],
            [
                "icon" => "cpu",
                "word" => "Software",
                "pronunciation" => "sóft-uér",
                "translation" => "Software",
                "desc" => "Programas de computador.",
            ],
            [
                "icon" => "git-branch",
                "word" => "Stack",
                "pronunciation" => "sték",
                "translation" => "Pilha",
                "desc" => "Estrutura de dados LIFO.",
            ],
            [
                "icon" => "share-2",
                "word" => "Socket",
                "pronunciation" => "só-ket",
                "translation" => "Socket",
                "desc" => "Comunicação em tempo real.",
            ],

            // T
            [
                "icon" => "git-branch",
                "word" => "Thread",
                "pronunciation" => "thrédi",
                "translation" => "Thread",
                "desc" => "Execução paralela.",
            ],
            [
                "icon" => "cpu",
                "word" => "Token",
                "pronunciation" => "tô-ken",
                "translation" => "Token",
                "desc" => "Chave de autenticação.",
            ],
            [
                "icon" => "database",
                "word" => "Table",
                "pronunciation" => "têi-bol",
                "translation" => "Tabela",
                "desc" => "Estrutura de dados em banco.",
            ],
            [
                "icon" => "terminal",
                "word" => "Terminal",
                "pronunciation" => "tér-mi-nal",
                "translation" => "Terminal",
                "desc" => "Interface de linha de comando.",
            ],
            [
                "icon" => "activity",
                "word" => "Timeout",
                "pronunciation" => "taim-áut",
                "translation" => "Tempo limite",
                "desc" => "Tempo máximo de espera.",
            ],
            [
                "icon" => "code",
                "word" => "Type",
                "pronunciation" => "táip",
                "translation" => "Tipo",
                "desc" => "Classificação de dados.",
            ],

            // U
            [
                "icon" => "user",
                "word" => "User",
                "pronunciation" => "iú-zer",
                "translation" => "Usuário",
                "desc" => "Pessoa que usa o sistema.",
            ],
            [
                "icon" => "link",
                "word" => "URL",
                "pronunciation" => "iu-ár-él",
                "translation" => "URL",
                "desc" => "Endereço na internet.",
            ],
            [
                "icon" => "layout",
                "word" => "UI",
                "pronunciation" => "iu-ai",
                "translation" => "Interface",
                "desc" => "Interface do usuário.",
            ],
            [
                "icon" => "cpu",
                "word" => "UX",
                "pronunciation" => "iu-éks",
                "translation" => "Experiência do usuário",
                "desc" => "Como o usuário interage.",
            ],
            [
                "icon" => "upload",
                "word" => "Upload",
                "pronunciation" => "âp-lôud",
                "translation" => "Enviar",
                "desc" => "Enviar dados para servidor.",
            ],
            [
                "icon" => "settings",
                "word" => "Update",
                "pronunciation" => "âp-deit",
                "translation" => "Atualizar",
                "desc" => "Modificar dados.",
            ],

            // V
            [
                "icon" => "activity",
                "word" => "Variable",
                "pronunciation" => "vê-ri-ah-bou",
                "translation" => "Variável",
                "desc" => "Armazena valores.",
            ],
            [
                "icon" => "cpu",
                "word" => "Virtual Machine",
                "pronunciation" => "vâr-tu-al ma-shín",
                "translation" => "Máquina virtual",
                "desc" => "Ambiente simulado.",
            ],
            [
                "icon" => "git-branch",
                "word" => "Version Control",
                "pronunciation" => "vér-shon con-trôul",
                "translation" => "Controle de versão",
                "desc" => "Gerenciar versões de código.",
            ],
            [
                "icon" => "database",
                "word" => "View",
                "pronunciation" => "viú",
                "translation" => "Visão",
                "desc" => "Consulta virtual no banco.",
            ],
            [
                "icon" => "cpu",
                "word" => "Validation",
                "pronunciation" => "va-li-dei-shun",
                "translation" => "Validação",
                "desc" => "Verificar dados.",
            ],
            [
                "icon" => "code",
                "word" => "Vue.js",
                "pronunciation" => "viú-djê-és",
                "translation" => "Vue.js",
                "desc" => "Framework JavaScript.",
            ],

            // W
            [
                "icon" => "globe",
                "word" => "Web",
                "pronunciation" => "uéb",
                "translation" => "Web",
                "desc" => "Sistema de páginas na internet.",
            ],
            [
                "icon" => "wifi",
                "word" => "Wi-Fi",
                "pronunciation" => "uai-fai",
                "translation" => "Wi-Fi",
                "desc" => "Rede sem fio.",
            ],
            [
                "icon" => "layout",
                "word" => "Website",
                "pronunciation" => "uéb-sait",
                "translation" => "Site",
                "desc" => "Conjunto de páginas web.",
            ],
            [
                "icon" => "box",
                "word" => "Widget",
                "pronunciation" => "uí-djét",
                "translation" => "Widget",
                "desc" => "Elemento de interface.",
            ],
            [
                "icon" => "cpu",
                "word" => "WebSocket",
                "pronunciation" => "uéb-só-ket",
                "translation" => "WebSocket",
                "desc" => "Comunicação em tempo real.",
            ],
            [
                "icon" => "terminal",
                "word" => "Workflow",
                "pronunciation" => "uórk-flôu",
                "translation" => "Fluxo de trabalho",
                "desc" => "Sequência de processos.",
            ],

            // X
            [
                "icon" => "file-text",
                "word" => "XML",
                "pronunciation" => "équis-em-él",
                "translation" => "XML",
                "desc" => "Formato de dados estruturados.",
            ],
            [
                "icon" => "cpu",
                "word" => "XSS",
                "pronunciation" => "éks-és-és",
                "translation" => "XSS",
                "desc" => "Ataque de script.",
            ],
            [
                "icon" => "activity",
                "word" => "XPath",
                "pronunciation" => "éks-páth",
                "translation" => "XPath",
                "desc" => "Consulta em XML.",
            ],
            [
                "icon" => "code",
                "word" => "Xcode",
                "pronunciation" => "éks-côud",
                "translation" => "Xcode",
                "desc" => "IDE da Apple.",
            ],
            [
                "icon" => "settings",
                "word" => "XAMPP",
                "pronunciation" => "zâmp",
                "translation" => "XAMPP",
                "desc" => "Servidor local.",
            ],
            [
                "icon" => "cpu",
                "word" => "x64",
                "pronunciation" => "éks-sixty-four",
                "translation" => "64 bits",
                "desc" => "Arquitetura de sistema.",
            ],

            // Y
            [
                "icon" => "settings",
                "word" => "YAML",
                "pronunciation" => "iá-mel",
                "translation" => "YAML",
                "desc" => "Formato de configuração.",
            ],
            [
                "icon" => "cpu",
                "word" => "Yield",
                "pronunciation" => "íeld",
                "translation" => "Yield",
                "desc" => "Retornar valor em execução.",
            ],
            [
                "icon" => "activity",
                "word" => "Yottabyte",
                "pronunciation" => "ió-ta-báit",
                "translation" => "Yottabyte",
                "desc" => "Unidade de dados gigante.",
            ],
            [
                "icon" => "code",
                "word" => "Yarn",
                "pronunciation" => "iárn",
                "translation" => "Yarn",
                "desc" => "Gerenciador de pacotes.",
            ],
            [
                "icon" => "cpu",
                "word" => "YUV",
                "pronunciation" => "uai-iu-vi",
                "translation" => "YUV",
                "desc" => "Formato de cor.",
            ],
            [
                "icon" => "box",
                "word" => "Yotta",
                "pronunciation" => "ió-ta",
                "translation" => "Yotta",
                "desc" => "Prefixo de grande escala.",
            ],

            // Z
            [
                "icon" => "archive",
                "word" => "Zip",
                "pronunciation" => "zíp",
                "translation" => "Compactar",
                "desc" => "Reduz tamanho de arquivos.",
            ],
            [
                "icon" => "cpu",
                "word" => "Zero-Day",
                "pronunciation" => "zí-ro déi",
                "translation" => "Zero-day",
                "desc" => "Falha recém descoberta.",
            ],
            [
                "icon" => "activity",
                "word" => "Zettabyte",
                "pronunciation" => "zé-ta-báit",
                "translation" => "Zettabyte",
                "desc" => "Unidade de dados.",
            ],
            [
                "icon" => "database",
                "word" => "Z-index",
                "pronunciation" => "zí índex",
                "translation" => "Z-index",
                "desc" => "Ordem de elementos na tela.",
            ],
            [
                "icon" => "cpu",
                "word" => "Zsh",
                "pronunciation" => "zí-és-eitch",
                "translation" => "Zsh",
                "desc" => "Shell de terminal.",
            ],
            [
                "icon" => "zap",
                "word" => "Zombie Process",
                "pronunciation" => "zóm-bi pró-sés",
                "translation" => "Processo zumbi",
                "desc" => "Processo finalizado mas não removido.",
            ],
        ]
    ]);
});

Route::apiResource('words', WordController::class);
Route::apiResource('categories', CategoryController::class);
Route::apiResource('tags', TagController::class);

Route::get('/admin', [AdminController::class, 'index']);
